### PR TITLE
Lesson 9

### PR DESCRIPTION
**Pull request by IharDorinel**

### CODE REVIEW

**Review by nikitik-nikita — COMMENTED** [review]
1. Correct a remark from a past pull request
2. It would be better to create one function. Then call it in the event handler by passing the desired argument
3. Colors must change infinitely

**Comment by IharDorinel** [comment]
@nikitik-nikita I've fixed it

**Comment by nikitik-nikita** [comment]
@IharDorinel need to resolve the conflict

**Comment by IharDorinel** [comment]
@nikitik-nikita resolved it

**Pull request merged**
